version: "3"
services:
  bitcoind:
    restart: unless-stopped
    container_name: btctest_bitcoind
    image: nicolasdorier/docker-bitcoin:0.19.1
    environment:
      BITCOIN_EXTRA_ARGS: |
        testnet=1
        server=1
        rpcport=8332
        rpcallowip=127.0.0.1
        rpcbind=127.0.0.1:8332
        port=18333
        whitelist=0.0.0.0/0
        maxmempool=500
        prune=550
        rpcuser=uname
        rpcpassword=pword
        # Options only for testnet
        [test]
        port=18333
        rpcport=18332
        rpcallowip=127.0.0.1
        rpcbind=127.0.0.1
        rpcbind=btctest_bitcoind
    # specify additional command line arguments here
    command: bitcoind -testnet
    healthcheck:
      test: ["CMD", "/entrypoint.sh", "bitcoin-cli", "getinfo"]
    ports:
      # change to 18333 if running testnet / 8333 for mainnet
      - "18333:18333"
    expose:
      - "18332"
    volumes:
      - /Volumes/rocket1tb/bitcoin-data:/data
      #- bitcoin-data:/data
    networks:
      - bitcoin
  bitcoin-cli:
    image: nicolasdorier/docker-bitcoin:0.19.1
    entrypoint: ["/entrypoint.sh", "bitcoin-cli"]
    command: bitcoin-cli -rpcuser=uname -rpcpassword=pword
    depends_on:
      - bitcoind
    network_mode: service:bitcoind

networks:
  bitcoin:

volumes:
  bitcoin-data:

